// Catálogo de moldes de texto do Kontor — DEFAULTS no código.
// É o fallback final da cascata (competição → instituição → global → aqui).
// Apagando tudo na base de dados, o produto continua a funcionar com estes textos.
// SEM IMPORTS — espelhado para supabase/functions/_shared/textos-catalogo.ts

export type CategoriaMolde = "cronica" | "jornal" | "board" | "interface";

export type VariavelMolde = { nome: string; descricao: string };

export type MoldeDefault = {
  chave: string;
  categoria: CategoriaMolde;
  rotulo: string;
  variaveis: VariavelMolde[];
  variantes: string[];
  exemplo: Record<string, string | number>;
};

const V = {
  turno: { nome: "turno", descricao: "Número do turno resolvido" },
  equipa: { nome: "equipa", descricao: "Nome da casa/equipa" },
  valor: { nome: "valor", descricao: "Valor da empresa formatado" },
  resultado: { nome: "resultado", descricao: "Resultado líquido formatado" },
  nome_pessoa: { nome: "nome_pessoa", descricao: "Nome do colaborador" },
  arquetipo: { nome: "arquetipo", descricao: "Arquétipo do colaborador" },
  papel: { nome: "papel", descricao: "Papel na organização" },
  anos: { nome: "anos", descricao: "Turnos de casa do colaborador" },
  quota: { nome: "quota", descricao: "Quota de mercado atual (%)" },
  quota_delta: { nome: "quota_delta", descricao: "Variação de quota em pontos" },
  montante: { nome: "montante", descricao: "Montante formatado" },
  rival: { nome: "rival", descricao: "Nome de outra casa" },
};

const EX = { turno: 7, equipa: "Marnera & Filhos" };

export const CATALOGO_MOLDES: MoldeDefault[] = [
  /* ───────────────────────────── CRÓNICA ───────────────────────────── */
  {
    chave: "cronica.primeiro_lucro",
    categoria: "cronica",
    rotulo: "Crónica · Primeiro lucro",
    variaveis: [V.turno, V.equipa, V.resultado],
    variantes: [
      "A casa fechou o turno {turno} com o seu primeiro lucro: {resultado}. Ficou assente que era possível.",
      "Pela primeira vez, o turno {turno} fechou com lucro: {resultado}. A casa respirou.",
    ],
    exemplo: { ...EX, resultado: "12,4 k€" },
  },
  {
    chave: "cronica.primeiro_prejuizo",
    categoria: "cronica",
    rotulo: "Crónica · Primeiro prejuízo",
    variaveis: [V.turno, V.equipa, V.resultado],
    variantes: [
      "Pela primeira vez, a casa fechou o turno em prejuízo: {resultado}. Ficou o registo por escrito.",
      "O turno {turno} trouxe o primeiro prejuízo da casa: {resultado}. Ninguém fingiu que não doeu.",
    ],
    exemplo: { ...EX, resultado: "−8,1 k€" },
  },
  {
    chave: "cronica.regresso_lucro",
    categoria: "cronica",
    rotulo: "Crónica · Regresso ao lucro",
    variaveis: [V.turno, V.resultado, { nome: "turnos_negativos", descricao: "Turnos consecutivos no vermelho" }],
    variantes: [
      "Depois de {turnos_negativos} turnos no vermelho, a casa voltou ao lucro no turno {turno} ({resultado}).",
      "O vermelho durou {turnos_negativos} turnos. No {turno}, a casa voltou a fechar em alta ({resultado}).",
    ],
    exemplo: { ...EX, resultado: "4,2 k€", turnos_negativos: 3 },
  },
  {
    chave: "cronica.serie_crescimento",
    categoria: "cronica",
    rotulo: "Crónica · Três turnos a valorizar",
    variaveis: [V.turno, { nome: "v2", descricao: "Valor em t−2" }, { nome: "v1", descricao: "Valor em t−1" }, { nome: "v0", descricao: "Valor atual" }],
    variantes: [
      "Terceiro turno consecutivo a valorizar: {v2} → {v1} → {v0}.",
      "Três turnos seguidos de subida: {v2}, depois {v1}, agora {v0}.",
    ],
    exemplo: { ...EX, v2: "310 k€", v1: "342 k€", v0: "388 k€" },
  },
  {
    chave: "cronica.serie_queda",
    categoria: "cronica",
    rotulo: "Crónica · Três turnos a perder valor",
    variaveis: [V.turno, { nome: "v2", descricao: "Valor em t−2" }, { nome: "v1", descricao: "Valor em t−1" }, { nome: "v0", descricao: "Valor atual" }],
    variantes: [
      "Terceiro turno consecutivo a perder valor: {v2} → {v1} → {v0}.",
      "A erosão continua: {v2} → {v1} → {v0}, três turnos a descer.",
    ],
    exemplo: { ...EX, v2: "388 k€", v1: "342 k€", v0: "310 k€" },
  },
  {
    chave: "cronica.subiu_ranking",
    categoria: "cronica",
    rotulo: "Crónica · Subida no mercado",
    variaveis: [V.turno, { nome: "atual", descricao: "Posição atual" }, { nome: "anterior", descricao: "Posição anterior" }],
    variantes: [
      "A casa subiu ao {atual}º lugar no mercado (era {anterior}º).",
      "Do {anterior}º para o {atual}º lugar: o turno {turno} valeu a subida.",
    ],
    exemplo: { ...EX, atual: 2, anterior: 4 },
  },
  {
    chave: "cronica.desceu_ranking",
    categoria: "cronica",
    rotulo: "Crónica · Descida no mercado",
    variaveis: [V.turno, { nome: "atual", descricao: "Posição atual" }, { nome: "anterior", descricao: "Posição anterior" }],
    variantes: [
      "A casa desceu para o {atual}º lugar (vinha do {anterior}º).",
      "Perdeu posição no turno {turno}: do {anterior}º para o {atual}º.",
    ],
    exemplo: { ...EX, atual: 4, anterior: 2 },
  },
  {
    chave: "cronica.quota_ganha",
    categoria: "cronica",
    rotulo: "Crónica · Quota ganha",
    variaveis: [V.turno, V.quota, V.quota_delta],
    variantes: [
      "Ganhou {quota_delta} pontos de quota, para {quota}%.",
      "A quota subiu {quota_delta} pontos no turno {turno}, fixando-se em {quota}%.",
    ],
    exemplo: { ...EX, quota: "24,6", quota_delta: "6,3" },
  },
  {
    chave: "cronica.quota_perdida",
    categoria: "cronica",
    rotulo: "Crónica · Quota perdida",
    variaveis: [V.turno, V.quota, V.quota_delta],
    variantes: [
      "Perdeu {quota_delta} pontos de quota, para {quota}%.",
      "A prateleira encolheu: menos {quota_delta} pontos de quota, agora {quota}%.",
    ],
    exemplo: { ...EX, quota: "18,2", quota_delta: "5,1" },
  },
  {
    chave: "cronica.credito_emergencia",
    categoria: "cronica",
    rotulo: "Crónica · Linha de crédito de emergência",
    variaveis: [V.turno, V.montante],
    variantes: [
      "A caixa fechou negativa e obrigou a recorrer a uma linha de crédito de emergência de {montante}, a juro punitivo.",
      "Sem caixa para fechar o turno {turno}, a casa aceitou {montante} de crédito de emergência — e o juro que vem com ele.",
    ],
    exemplo: { ...EX, montante: "50 k€" },
  },
  {
    chave: "cronica.teto_divida",
    categoria: "cronica",
    rotulo: "Crónica · Teto de dívida ultrapassado",
    variaveis: [V.turno],
    variantes: [
      "A dívida ultrapassou o teto que a casa tinha fixado para si própria.",
      "O limite de dívida que a casa se impôs foi ultrapassado no turno {turno}.",
    ],
    exemplo: { ...EX },
  },
  {
    chave: "cronica.greve",
    categoria: "cronica",
    rotulo: "Crónica · Greve",
    variaveis: [V.turno],
    variantes: [
      "Houve greve nas linhas. A produção do turno saiu bem abaixo do previsto.",
      "As linhas pararam no turno {turno}. O que se produziu ficou muito aquém do planeado.",
    ],
    exemplo: { ...EX },
  },
  {
    chave: "cronica.push_output",
    categoria: "cronica",
    rotulo: "Crónica · Produção acima do previsto",
    variaveis: [V.turno],
    variantes: [
      "A moral alta empurrou a produção para além do previsto: o turno rendeu mais do que se pediu.",
      "Com a casa animada, o turno {turno} rendeu acima do que se tinha pedido às linhas.",
    ],
    exemplo: { ...EX },
  },
  {
    chave: "cronica.breakthrough",
    categoria: "cronica",
    rotulo: "Crónica · Avanço de I&D",
    variaveis: [V.turno],
    variantes: [
      "O laboratório teve uma noite feliz: um avanço inesperado destrancou trabalho de meses.",
      "No turno {turno}, o laboratório encontrou o atalho que procurava há muito.",
    ],
    exemplo: { ...EX },
  },
  {
    chave: "cronica.saida_talento",
    categoria: "cronica",
    rotulo: "Crónica · Saída de talento",
    variaveis: [V.turno],
    variantes: [
      "A casa perdeu um talento para a concorrência. A investigação ficou mais pobre.",
      "Um dos melhores saiu no turno {turno}. Levou consigo mais do que a secretária.",
    ],
    exemplo: { ...EX },
  },
  {
    chave: "cronica.burnout",
    categoria: "cronica",
    rotulo: "Crónica · Esgotamento",
    variaveis: [V.turno],
    variantes: [
      "Registaram-se casos de esgotamento. O ritmo cobrou preço.",
      "O ritmo do turno {turno} deixou marcas: houve esgotamentos.",
    ],
    exemplo: { ...EX },
  },
  {
    chave: "cronica.id_desbloqueado",
    categoria: "cronica",
    rotulo: "Crónica · Nó de I&D desbloqueado",
    variaveis: [V.turno, { nome: "no", descricao: "Identificador do nó de I&D" }],
    variantes: [
      "O laboratório desbloqueou um novo nó de I&D ({no}).",
      "Mais uma porta aberta na árvore de I&D: {no}.",
    ],
    exemplo: { ...EX, no: "FINE" },
  },
  {
    chave: "cronica.decisoes_ajustadas",
    categoria: "cronica",
    rotulo: "Crónica · Decisões ajustadas",
    variaveis: [V.turno, { nome: "n", descricao: "Número de decisões ajustadas" }],
    variantes: [
      "Nem tudo o que se decidiu chegou a acontecer: {n} decisão(ões) foram anuladas ou ajustadas por precedência.",
      "O turno {turno} corrigiu a mão de quem decidiu: {n} decisão(ões) não sobreviveram às regras da casa.",
    ],
    exemplo: { ...EX, n: 2 },
  },
  {
    chave: "cronica.contratacao",
    categoria: "cronica",
    rotulo: "Crónica · Contratação",
    variaveis: [V.turno],
    variantes: [
      "Entrou alguém para o chão de fábrica no turno {turno}.",
      "A casa abriu a porta a gente nova no turno {turno}.",
    ],
    exemplo: { ...EX },
  },
  {
    chave: "cronica.saida_veterano",
    categoria: "cronica",
    rotulo: "Crónica · Saída de veterano",
    variaveis: [V.turno, V.nome_pessoa, V.anos],
    variantes: [
      "A casa despediu-se de {nome_pessoa}, veterano que aqui esteve {anos} turnos. Poucos ficaram indiferentes.",
      "Ao fim de {anos} turnos, {nome_pessoa} saiu. Quem ficou não falou de outra coisa.",
    ],
    exemplo: { ...EX, nome_pessoa: "Amélia Craveiro", anos: 6 },
  },
  {
    chave: "cronica.despedimento",
    categoria: "cronica",
    rotulo: "Crónica · Despedimento",
    variaveis: [V.turno, V.nome_pessoa, V.anos],
    variantes: [
      "{nome_pessoa} foi despedido(a) no turno {turno}.",
      "O turno {turno} levou {nome_pessoa} para fora do portão.",
    ],
    exemplo: { ...EX, nome_pessoa: "Rui Vasques", anos: 2 },
  },
  {
    chave: "cronica.promocao_aprendiz",
    categoria: "cronica",
    rotulo: "Crónica · Promoção de aprendiz",
    variaveis: [V.turno, V.nome_pessoa, V.papel],
    variantes: [
      "{nome_pessoa}, que entrou como aprendiz, foi promovido(a) a {papel}. A casa cresceu-lhe dentro.",
      "De aprendiz a {papel}: {nome_pessoa} subiu no turno {turno}.",
    ],
    exemplo: { ...EX, nome_pessoa: "Inês Bragança", papel: "supervisor" },
  },
  {
    chave: "cronica.promocao",
    categoria: "cronica",
    rotulo: "Crónica · Promoção",
    variaveis: [V.turno, V.nome_pessoa, V.papel],
    variantes: [
      "{nome_pessoa} foi promovido(a) a {papel}.",
      "No turno {turno}, {nome_pessoa} passou a {papel}.",
    ],
    exemplo: { ...EX, nome_pessoa: "Jorge Almada", papel: "chefe de linha" },
  },
  {
    chave: "cronica.promocao_merito",
    categoria: "cronica",
    rotulo: "Crónica · Promoção de mérito",
    variaveis: [V.turno, V.nome_pessoa],
    variantes: [
      "{nome_pessoa} teve promoção de mérito.",
      "O mérito de {nome_pessoa} foi reconhecido no turno {turno}.",
    ],
    exemplo: { ...EX, nome_pessoa: "Sara Tovar" },
  },
  {
    chave: "cronica.silencio",
    categoria: "cronica",
    rotulo: "Crónica · Turno sem registo",
    variaveis: [V.turno],
    variantes: [
      "Turno {turno} — sem registo digno de nota.",
      "Turno {turno} — a casa trabalhou e pouco mais houve a assinalar.",
    ],
    exemplo: { ...EX },
  },

  /* ───────────────────────────── JORNAL ───────────────────────────── */
  {
    chave: "jornal.manchete.falencia.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Manchete de falência (título)",
    variaveis: [V.turno, { nome: "nomes", descricao: "Nomes das casas falidas" }, { nome: "n", descricao: "Número de casas falidas" }],
    variantes: ["Casa {nomes} colapsa na praça", "Fecho de portas: {nomes}"],
    exemplo: { ...EX, nomes: "Sousa & Irmãos", n: 1 },
  },
  {
    chave: "jornal.manchete.falencia.sub",
    categoria: "jornal",
    rotulo: "Jornal · Manchete de falência (subtítulo)",
    variaveis: [V.turno, { nome: "competicao", descricao: "Nome da praça/competição" }, { nome: "nomes", descricao: "Nomes das casas falidas" }],
    variantes: ["A praça de {competicao} regista o fecho no turno {turno}."],
    exemplo: { ...EX, competicao: "Hansa de Lisboa", nomes: "Sousa & Irmãos" },
  },
  {
    chave: "jornal.manchete.subida.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Maior subida (título)",
    variaveis: [V.turno, V.rival, { nome: "delta", descricao: "Variação de valor formatada" }],
    variantes: ["{rival} dispara {delta} em valor", "{rival} ganha {delta} e sacode a praça"],
    exemplo: { ...EX, rival: "Vilar & Companhia", delta: "42k €" },
  },
  {
    chave: "jornal.manchete.subida.sub",
    categoria: "jornal",
    rotulo: "Jornal · Maior subida (subtítulo)",
    variaveis: [V.rival, V.valor, { nome: "delta", descricao: "Variação de valor formatada" }],
    variantes: ["Passa a valer {valor} — a maior subida do turno."],
    exemplo: { ...EX, rival: "Vilar & Companhia", valor: "388k €", delta: "42k €" },
  },
  {
    chave: "jornal.manchete.queda.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Maior queda (título)",
    variaveis: [V.turno, V.rival, { nome: "delta", descricao: "Queda de valor formatada" }],
    variantes: ["{rival} perde {delta} em valor", "{delta} evaporam-se na {rival}"],
    exemplo: { ...EX, rival: "Sousa & Irmãos", delta: "31k €" },
  },
  {
    chave: "jornal.manchete.queda.sub",
    categoria: "jornal",
    rotulo: "Jornal · Maior queda (subtítulo)",
    variaveis: [V.rival, V.valor, { nome: "delta", descricao: "Queda de valor formatada" }],
    variantes: ["Recua para {valor} — a maior queda do turno."],
    exemplo: { ...EX, rival: "Sousa & Irmãos", valor: "180k €", delta: "31k €" },
  },
  {
    chave: "jornal.manchete.lideranca.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Líder destacado (título)",
    variaveis: [V.turno, { nome: "lider", descricao: "Casa líder" }],
    variantes: ["{lider} destaca-se e lidera a praça", "{lider} governa a praça sem contestação"],
    exemplo: { ...EX, lider: "Marnera & Filhos" },
  },
  {
    chave: "jornal.manchete.lideranca.sub",
    categoria: "jornal",
    rotulo: "Jornal · Líder destacado (subtítulo)",
    variaveis: [{ nome: "lider", descricao: "Casa líder" }, { nome: "segundo", descricao: "Segunda casa" }, V.valor, { nome: "folga", descricao: "Distância para a segunda" }],
    variantes: ["Vale {valor}, distância {folga} sobre {segundo}."],
    exemplo: { ...EX, lider: "Marnera & Filhos", segundo: "Vilar & Companhia", valor: "512k €", folga: "180k €" },
  },
  {
    chave: "jornal.manchete.praca.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Praça disputada (título)",
    variaveis: [{ nome: "lider", descricao: "Casa líder" }, { nome: "segundo", descricao: "Segunda casa" }],
    variantes: ["{lider} à cabeça, {segundo} a curta distância", "{lider} e {segundo} separadas por um fio"],
    exemplo: { ...EX, lider: "Marnera & Filhos", segundo: "Vilar & Companhia" },
  },
  {
    chave: "jornal.manchete.praca.sub",
    categoria: "jornal",
    rotulo: "Jornal · Praça disputada (subtítulo)",
    variaveis: [{ nome: "folga", descricao: "Diferença entre as duas primeiras" }],
    variantes: ["Diferença de apenas {folga} entre as duas primeiras casas."],
    exemplo: { ...EX, folga: "6k €" },
  },
  {
    chave: "jornal.manchete.lucro.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Manchete de lucro da casa",
    variaveis: [V.turno, V.equipa, V.resultado],
    variantes: ["{equipa} fecha turno com lucro de {resultado}"],
    exemplo: { ...EX, resultado: "12k €" },
  },
  {
    chave: "jornal.manchete.prejuizo.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Manchete de prejuízo da casa",
    variaveis: [V.turno, V.equipa, V.resultado],
    variantes: ["{equipa} apura prejuízo de {resultado}"],
    exemplo: { ...EX, resultado: "8k €" },
  },
  {
    chave: "jornal.manchete.sem_eventos.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Turno sem manchete",
    variaveis: [V.turno],
    variantes: ["Turno {turno} sem eventos de mercado dignos de manchete"],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.economia.ciclo",
    categoria: "jornal",
    rotulo: "Jornal · Fase do ciclo económico",
    variaveis: [{ nome: "fase", descricao: "Fase macroeconómica" }],
    variantes: ["Fase macroeconómica: {fase}"],
    exemplo: { ...EX, fase: "expansão" },
  },
  {
    chave: "jornal.economia.juro_variacao",
    categoria: "jornal",
    rotulo: "Jornal · Juro em variação",
    variaveis: [{ nome: "direcao", descricao: "sobe ou desce" }, { nome: "juro", descricao: "Juro base (%)" }, { nome: "delta", descricao: "Variação em pontos" }],
    variantes: ["Juro base {direcao} para {juro}%"],
    exemplo: { ...EX, direcao: "sobe", juro: "4,25", delta: "0,50" },
  },
  {
    chave: "jornal.economia.juro_variacao.sub",
    categoria: "jornal",
    rotulo: "Jornal · Juro em variação (subtítulo)",
    variaveis: [{ nome: "sinal", descricao: "Sinal + ou −" }, { nome: "delta", descricao: "Variação em pontos" }],
    variantes: ["Variação de {sinal}{delta} pontos."],
    exemplo: { ...EX, sinal: "+", delta: "0,50" },
  },
  {
    chave: "jornal.economia.juro_estavel",
    categoria: "jornal",
    rotulo: "Jornal · Juro estável",
    variaveis: [{ nome: "juro", descricao: "Juro base (%)" }],
    variantes: ["Juro base estável em {juro}%"],
    exemplo: { ...EX, juro: "4,00" },
  },
  {
    chave: "jornal.economia.inflacao",
    categoria: "jornal",
    rotulo: "Jornal · Inflação",
    variaveis: [{ nome: "direcao", descricao: "acelera, abranda ou mantém-se" }, { nome: "inflacao", descricao: "Inflação (%)" }],
    variantes: ["Inflação {direcao} em {inflacao}%"],
    exemplo: { ...EX, direcao: "acelera", inflacao: "3,2" },
  },
  {
    chave: "jornal.economia.confianca",
    categoria: "jornal",
    rotulo: "Jornal · Confiança",
    variaveis: [{ nome: "confianca", descricao: "Índice de confiança" }],
    variantes: ["Índice de confiança em {confianca}"],
    exemplo: { ...EX, confianca: 102 },
  },
  {
    chave: "jornal.economia.confianca.sub",
    categoria: "jornal",
    rotulo: "Jornal · Confiança (subtítulo)",
    variaveis: [{ nome: "crescimento", descricao: "Crescimento (%)" }],
    variantes: ["Crescimento {crescimento}%."],
    exemplo: { ...EX, crescimento: "1,8" },
  },
  {
    chave: "jornal.opiniao.autor",
    categoria: "jornal",
    rotulo: "Jornal · Nome do colunista",
    variaveis: [],
    variantes: ["Fradique da Praça"],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.opiniao.concentracao.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Opinião — concentração (título)",
    variaveis: [V.turno, { nome: "hhi", descricao: "Índice de concentração" }],
    variantes: ["O tabuleiro está a ficar pequeno", "Poucos nomes, muita praça"],
    exemplo: { ...EX, hhi: 4800 },
  },
  {
    chave: "jornal.opiniao.concentracao.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Opinião — concentração (corpo)",
    variaveis: [V.turno, { nome: "hhi", descricao: "Índice de concentração" }],
    variantes: [
      "Diz-se pela praça que a concorrência é saudável. Neste turno {turno}, a concentração de quota fala por si — poucos nomes, muita margem, e um índice de dominância a rondar os {hhi}. Quem vive à sombra dos gigantes que se cubra: a próxima geada não perdoa os pequenos.",
    ],
    exemplo: { ...EX, hhi: 4800 },
  },
  {
    chave: "jornal.opiniao.fragmentacao.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Opinião — fragmentação (título)",
    variaveis: [V.turno, { nome: "delta", descricao: "Queda do índice de concentração" }],
    variantes: ["A praça fragmenta-se", "Espaço para todos os cotovelos"],
    exemplo: { ...EX, delta: 620 },
  },
  {
    chave: "jornal.opiniao.fragmentacao.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Opinião — fragmentação (corpo)",
    variaveis: [V.turno, { nome: "delta", descricao: "Queda do índice de concentração" }],
    variantes: [
      "Ao contrário do turno anterior, ninguém se destaca de forma insolente. A concentração cede {delta} pontos e há espaço para todos os cotovelos. É costume dizer-se que mercados abertos convidam a estratégias tímidas — este colunista discorda.",
    ],
    exemplo: { ...EX, delta: 620 },
  },
  {
    chave: "jornal.opiniao.guerra_precos.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Opinião — guerra de preços (título)",
    variaveis: [V.turno, { nome: "delta", descricao: "Queda média de preços" }],
    variantes: ["Guerra de preços declarada", "A margem é um luxo"],
    exemplo: { ...EX, delta: "5,4" },
  },
  {
    chave: "jornal.opiniao.guerra_precos.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Opinião — guerra de preços (corpo)",
    variaveis: [V.turno, { nome: "delta", descricao: "Queda média de preços" }],
    variantes: [
      "A tabela caiu {delta} pontos em média e alguém, algures, decidiu que a margem é um luxo. Os consumidores agradecem no imediato; os contabilistas hão-de ajustar as expectativas no fim do trimestre. Aviso à navegação: quem entra em guerras de preço raramente escreve as memórias.",
    ],
    exemplo: { ...EX, delta: "5,4" },
  },
  {
    chave: "jornal.opiniao.qualidade.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Opinião — corrida à qualidade (título)",
    variaveis: [V.turno, { nome: "delta", descricao: "Subida do tier médio" }],
    variantes: ["Corrida à qualidade", "A fasquia sobe — e a fatura também"],
    exemplo: { ...EX, delta: "0,4" },
  },
  {
    chave: "jornal.opiniao.qualidade.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Opinião — corrida à qualidade (corpo)",
    variaveis: [V.turno, { nome: "delta", descricao: "Subida do tier médio" }],
    variantes: [
      "Sobe o tier médio dos produtos {delta} degraus. Traduzindo: as casas estão a subir a fasquia e a passar a fatura ao cliente. Falta ver se o cliente paga com sorriso ou com carteira encolhida.",
    ],
    exemplo: { ...EX, delta: "0,4" },
  },
  {
    chave: "jornal.opiniao.precos_alta.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Opinião — preços em alta (título)",
    variaveis: [V.turno, { nome: "delta", descricao: "Subida média de preços" }],
    variantes: ["Preços em alta — coragem ou distração?"],
    exemplo: { ...EX, delta: "3,1" },
  },
  {
    chave: "jornal.opiniao.precos_alta.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Opinião — preços em alta (corpo)",
    variaveis: [V.turno, { nome: "delta", descricao: "Subida média de preços" }],
    variantes: [
      "Os preços médios sobem {delta} pontos face ao turno anterior. Há quem chame a isto pricing power; outros preferem chamar-lhe teste de paciência. O mercado dirá.",
    ],
    exemplo: { ...EX, delta: "3,1" },
  },
  {
    chave: "jornal.opiniao.calmo.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Opinião — turno calmo (título)",
    variaveis: [V.turno],
    variantes: ["Um turno sem sobressaltos"],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.opiniao.calmo.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Opinião — turno calmo (corpo)",
    variaveis: [V.turno],
    variantes: [
      "Se a virtude estivesse em não mexer, teríamos hoje um turno virtuoso. As posições consolidam-se, as manchetes escasseiam e este colunista prepara-se para a próxima ronda com esperança renovada — ou, pelo menos, com café mais forte.",
    ],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.anuncio.marketing.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Anúncio de marketing forte (título)",
    variaveis: [V.equipa, { nome: "equipa_maiusculas", descricao: "Nome da casa em maiúsculas" }],
    variantes: ["{equipa_maiusculas} — a marca que enche a rua"],
    exemplo: { ...EX, equipa_maiusculas: "MARNERA & FILHOS" },
  },
  {
    chave: "jornal.anuncio.marketing.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Anúncio de marketing forte (corpo)",
    variaveis: [V.equipa],
    variantes: ["Da praça ao porto, todos falam. Descubra o catálogo da estação e sinta a diferença de uma casa que investe em si."],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.anuncio.exportacao.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Anúncio de exportação (título)",
    variaveis: [V.equipa],
    variantes: ["{equipa} anuncia no porto"],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.anuncio.exportacao.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Anúncio de exportação (corpo)",
    variaveis: [V.equipa],
    variantes: ["Mercadoria pronta para embarque. Contactos preferenciais para clientes de além-mar."],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.anuncio.qualidade.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Anúncio de qualidade (título)",
    variaveis: [V.equipa],
    variantes: ["{equipa} — qualidade superior"],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.anuncio.qualidade.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Anúncio de qualidade (corpo)",
    variaveis: [V.equipa],
    variantes: ["Peças de tier alto, acabamento cuidado. Recomenda-se a exigentes."],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.anuncio.agressiva.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Anúncio de postura agressiva (título)",
    variaveis: [V.equipa],
    variantes: ["{equipa} avança"],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.anuncio.agressiva.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Anúncio de postura agressiva (corpo)",
    variaveis: [V.equipa],
    variantes: ["Nova postura, novos preços. Aproxime-se e negocie."],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.anuncio.lider.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Anúncio da casa líder (título)",
    variaveis: [V.rival],
    variantes: ["Casa {rival} — reputação com selo"],
    exemplo: { ...EX, rival: "Vilar & Companhia" },
  },
  {
    chave: "jornal.anuncio.lider.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Anúncio da casa líder (corpo)",
    variaveis: [V.rival, V.valor],
    variantes: ["A liderar a praça com {valor}. Encomendas atendidas por ordem de chegada."],
    exemplo: { ...EX, rival: "Vilar & Companhia", valor: "512k €" },
  },
  {
    chave: "jornal.anuncio.expansao.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Anúncio de expansão (título)",
    variaveis: [V.rival],
    variantes: ["{rival} anuncia expansão"],
    exemplo: { ...EX, rival: "Vilar & Companhia" },
  },
  {
    chave: "jornal.anuncio.expansao.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Anúncio de expansão (corpo)",
    variaveis: [V.rival],
    variantes: ["Nova capacidade instalada. Contratações em curso."],
    exemplo: { ...EX, rival: "Vilar & Companhia" },
  },
  {
    chave: "jornal.anuncio.liquidacao.titulo",
    categoria: "jornal",
    rotulo: "Jornal · Anúncio de liquidação (título)",
    variaveis: [V.rival],
    variantes: ["{rival} — liquidação de existências"],
    exemplo: { ...EX, rival: "Sousa & Irmãos" },
  },
  {
    chave: "jornal.anuncio.liquidacao.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Anúncio de liquidação (corpo)",
    variaveis: [V.rival],
    variantes: ["Aproveite condições especiais enquanto durar o stock."],
    exemplo: { ...EX, rival: "Sousa & Irmãos" },
  },
  {
    chave: "jornal.carta.greve.autor",
    categoria: "jornal",
    rotulo: "Jornal · Carta sobre greve (autor)",
    variaveis: [],
    variantes: ["Um operário anónimo"],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.carta.greve.assunto",
    categoria: "jornal",
    rotulo: "Jornal · Carta sobre greve (assunto)",
    variaveis: [],
    variantes: ["Paragem no chão de fábrica"],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.carta.greve.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Carta sobre greve (corpo)",
    variaveis: [V.turno],
    variantes: [
      "Senhor Diretor: escrevo-lhe com a mão suja de graxa e a paciência gasta. A greve não é capricho — é a soma de turnos calados e promessas por cumprir. Deem-nos o que é justo, e voltamos ao torno.",
    ],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.carta.breakthrough.autor",
    categoria: "jornal",
    rotulo: "Jornal · Carta sobre avanço de I&D (autor)",
    variaveis: [],
    variantes: ["Um investigador entusiasmado"],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.carta.breakthrough.assunto",
    categoria: "jornal",
    rotulo: "Jornal · Carta sobre avanço de I&D (assunto)",
    variaveis: [],
    variantes: ["Um passo em frente"],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.carta.breakthrough.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Carta sobre avanço de I&D (corpo)",
    variaveis: [V.turno],
    variantes: [
      "Senhor Diretor: permita-me a euforia — o laboratório encontrou o que procurava. Não é ainda um milagre, mas é seguramente uma vantagem. Peço que a administração dê o tempo justo antes de exigir o retorno.",
    ],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.carta.credito.autor",
    categoria: "jornal",
    rotulo: "Jornal · Carta sobre crédito (autor)",
    variaveis: [],
    variantes: ["Um credor prudente"],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.carta.credito.assunto",
    categoria: "jornal",
    rotulo: "Jornal · Carta sobre crédito (assunto)",
    variaveis: [],
    variantes: ["Sobre a nova linha de crédito"],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.carta.credito.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Carta sobre crédito (corpo)",
    variaveis: [V.turno],
    variantes: [
      "Senhor Diretor: aceito com desagrado que a casa tenha recorrido à linha automática. Compreendo a urgência, mas os juros não perdoam sentimentos. Aguardo o plano de amortização com o interesse de sempre.",
    ],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.carta.despedimento.autor",
    categoria: "jornal",
    rotulo: "Jornal · Carta sobre despedimento (autor)",
    variaveis: [],
    variantes: ["Um antigo colega"],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.carta.despedimento.assunto",
    categoria: "jornal",
    rotulo: "Jornal · Carta sobre despedimento (assunto)",
    variaveis: [],
    variantes: ["Sobre a despedida"],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.carta.despedimento.corpo",
    categoria: "jornal",
    rotulo: "Jornal · Carta sobre despedimento (corpo)",
    variaveis: [V.turno],
    variantes: [
      "Senhor Diretor: a decisão foi tomada e o portão fechou-se. Fica o registo: quem parte leva o que sabia, e quem fica lembra-se. Que a próxima admissão seja feita com o mesmo cuidado com que se assinou a saída.",
    ],
    exemplo: { ...EX },
  },
  {
    chave: "jornal.necrologia",
    categoria: "jornal",
    rotulo: "Jornal · Necrologia de uma casa",
    variaveis: [V.rival, V.valor, V.turno],
    variantes: [
      "Casa {rival} — encerrou portas no turno atual, após ter valido {valor}. Deixa saudades entre os credores.",
      "Casa {rival} — fecho no turno {turno}. Valia {valor} e agora é memória.",
    ],
    exemplo: { ...EX, rival: "Sousa & Irmãos", valor: "180k €" },
  },

  /* ───────────────────────────── BOARD ───────────────────────────── */
  {
    chave: "board.missao",
    categoria: "board",
    rotulo: "Board · Missão da Administração",
    variaveis: [V.equipa],
    variantes: [
      "Consolidar a casa como referência ibérica em mobiliário funcional e durável, mantendo margem operacional acima de 20% até ao fim do mandato.",
    ],
    exemplo: { ...EX },
  },
  {
    chave: "board.missao.assinatura",
    categoria: "board",
    rotulo: "Board · Assinatura da missão",
    variaveis: [],
    variantes: ["Presidente do Conselho de Administração"],
    exemplo: { ...EX },
  },

  /* ─────────────────────────── INTERFACE ─────────────────────────── */
  {
    chave: "interface.pesquisa.CEO",
    categoria: "interface",
    rotulo: "Interface · Pesquisa do CEO",
    variaveis: [],
    variantes: ["Revela pistas sobre um rival: perfil aparente, preços e capacidade estimados. A informação pode chegar com 1 turno de atraso."],
    exemplo: {},
  },
  {
    chave: "interface.pesquisa.CFO",
    categoria: "interface",
    rotulo: "Interface · Pesquisa do CFO",
    variaveis: [],
    variantes: ["Revela a trajetória provável da economia (juro, inflação, crescimento e confiança) nos próximos turnos."],
    exemplo: {},
  },
  {
    chave: "interface.pesquisa.COO",
    categoria: "interface",
    rotulo: "Interface · Pesquisa do COO",
    variaveis: [],
    variantes: ["Revela o progresso da I&D e a distância ao próximo breakthrough — produto ou processo."],
    exemplo: {},
  },
  {
    chave: "interface.pesquisa.CMO",
    categoria: "interface",
    rotulo: "Interface · Pesquisa do CMO",
    variaveis: [],
    variantes: ["Revela que linhas e atributos o mercado procura e a sensibilidade ao preço por segmento."],
    exemplo: {},
  },
  {
    chave: "interface.pesquisa.CHRO",
    categoria: "interface",
    rotulo: "Interface · Escuta do CHRO",
    variaveis: [],
    variantes: ["Sonda um colaborador aleatório — motivação, stress e necessidades aparentes."],
    exemplo: {},
  },
  {
    chave: "interface.postura.Crescimento",
    categoria: "interface",
    rotulo: "Interface · Postura Crescimento",
    variaveis: [],
    variantes: ["Prioriza a expansão de vendas e capacidade produtiva."],
    exemplo: {},
  },
  {
    chave: "interface.postura.Rentabilidade",
    categoria: "interface",
    rotulo: "Interface · Postura Rentabilidade",
    variaveis: [],
    variantes: ["Foca a margem e a geração de caixa."],
    exemplo: {},
  },
  {
    chave: "interface.postura.Quota",
    categoria: "interface",
    rotulo: "Interface · Postura Quota",
    variaveis: [],
    variantes: ["Ganhar mercado mesmo com margem menor."],
    exemplo: {},
  },
  {
    chave: "interface.postura.Equilibrio",
    categoria: "interface",
    rotulo: "Interface · Postura Equilíbrio",
    variaveis: [],
    variantes: ["Mistura crescimento, margem e prudência."],
    exemplo: {},
  },
  {
    chave: "interface.tier.standard",
    categoria: "interface",
    rotulo: "Interface · Tier Standard",
    variaveis: [],
    variantes: ["Sem I&D. Custo base."],
    exemplo: {},
  },
  {
    chave: "interface.tier.fine",
    categoria: "interface",
    rotulo: "Interface · Tier Fine",
    variaveis: [],
    variantes: ["Requer FINE. +58% mão-de-obra, melhor qualidade."],
    exemplo: {},
  },
  {
    chave: "interface.tier.artisan",
    categoria: "interface",
    rotulo: "Interface · Tier Artisan",
    variaveis: [],
    variantes: ["Requer ARTISAN. +110% mão-de-obra, top qualidade."],
    exemplo: {},
  },
  {
    chave: "interface.ritmo.ferias",
    categoria: "interface",
    rotulo: "Interface · Ritmo Férias",
    variaveis: [],
    variantes: ["Reinicia o stress mas produz ~0 no turno."],
    exemplo: {},
  },
  {
    chave: "interface.ritmo.folga",
    categoria: "interface",
    rotulo: "Interface · Ritmo Folga",
    variaveis: [],
    variantes: ["Alivia stress; reduz capacidade."],
    exemplo: {},
  },
  {
    chave: "interface.ritmo.normal",
    categoria: "interface",
    rotulo: "Interface · Ritmo Normal",
    variaveis: [],
    variantes: ["Ritmo base (160 h/trabalhador)."],
    exemplo: {},
  },
  {
    chave: "interface.ritmo.horas_extra",
    categoria: "interface",
    rotulo: "Interface · Ritmo Horas extra",
    variaveis: [],
    variantes: ["+40 h/trabalhador; mão-de-obra a 1,5×; +stress."],
    exemplo: {},
  },
  {
    chave: "interface.id.interno",
    categoria: "interface",
    rotulo: "Interface · I&D interno",
    variaveis: [],
    variantes: ["Investigadores desenvolvem ao longo dos turnos (custo = salário dos investigadores)."],
    exemplo: {},
  },
  {
    chave: "interface.id.licenca",
    categoria: "interface",
    rotulo: "Interface · I&D por licença",
    variaveis: [],
    variantes: ["Pagamento único de €45.000 — desbloqueia já a tecnologia."],
    exemplo: {},
  },
  {
    chave: "interface.canal.grosso",
    categoria: "interface",
    rotulo: "Interface · Canal Grosso",
    variaveis: [],
    variantes: ["Preço realizado ×0,85, +10% alcance — mais volume a margem menor."],
    exemplo: {},
  },
  {
    chave: "interface.canal.direto",
    categoria: "interface",
    rotulo: "Interface · Canal Direto",
    variaveis: [],
    variantes: ["Preço ×1,00, marca +2/turno, −10% alcance; marketing rende ×1,15."],
    exemplo: {},
  },
  {
    chave: "interface.canal.exportacao",
    categoria: "interface",
    rotulo: "Interface · Canal Exportação",
    variaveis: [],
    variantes: ["Preço ×0,72; abre procura externa adicional."],
    exemplo: {},
  },
  {
    chave: "interface.landing.tag",
    categoria: "interface",
    rotulo: "Landing · Etiqueta do topo",
    variaveis: [],
    variantes: ["Ensino superior · Gestão · Simulação"],
    exemplo: {},
  },
  {
    chave: "interface.landing.titulo",
    categoria: "interface",
    rotulo: "Landing · Título principal",
    variaveis: [],
    variantes: ["A gestão de uma empresa, aprendida a decidir."],
    exemplo: {},
  },
  {
    chave: "interface.landing.subtitulo",
    categoria: "interface",
    rotulo: "Landing · Subtítulo",
    variaveis: [],
    variantes: [
      "Em equipa, cada aluno assume uma pasta executiva e gere uma empresa num mercado vivo e único a cada jogo. Decidem juntos, semana após semana, e o mercado responde. Vence quem criar mais valor.",
    ],
    exemplo: {},
  },
];

export const MOLDES_POR_CHAVE: Record<string, MoldeDefault> = (() => {
  const m: Record<string, MoldeDefault> = {};
  for (const x of CATALOGO_MOLDES) m[x.chave] = x;
  return m;
})();

/** Defaults no código: chave → variantes. Fallback final da cascata. */
export const DEFAULTS_TEXTO: Record<string, string[]> = (() => {
  const m: Record<string, string[]> = {};
  for (const x of CATALOGO_MOLDES) m[x.chave] = x.variantes;
  return m;
})();

export const CATEGORIAS: { id: CategoriaMolde; rotulo: string; nota: string }[] = [
  { id: "cronica", rotulo: "Crónica", nota: "A casa a falar de si própria." },
  { id: "jornal", rotulo: "Jornal", nota: "O mundo a falar: manchetes, economia, opinião, anúncios." },
  { id: "board", rotulo: "Board", nota: "Missão da Administração — o texto mais personalizável por turma." },
  { id: "interface", rotulo: "Interface", nota: "Explicações dos controlos, pesquisas e landing." },
];
