/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EntrarHansaRouteImport } from './routes/entrar-hansa'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthConfirmadoRouteImport } from './routes/auth.confirmado'
import { Route as AuthenticatedNovaHansaRouteImport } from './routes/_authenticated/nova-hansa'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedPainelSuperAdminRouteImport } from './routes/_authenticated/painel.super-admin'
import { Route as AuthenticatedPainelJogadorHomeRouteImport } from './routes/_authenticated/painel.jogador-home'
import { Route as AuthenticatedPainelAdminEscolarRouteImport } from './routes/_authenticated/painel.admin-escolar'
import { Route as AuthenticatedPainelProfessorIndexRouteImport } from './routes/_authenticated/painel.professor.index'
import { Route as AuthenticatedPainelJogadorIndexRouteImport } from './routes/_authenticated/painel.jogador.index'
import { Route as ApiPublicHooksResolverTickRouteImport } from './routes/api/public/hooks/resolver-tick'
import { Route as AuthenticatedPainelJogadorCompeticaoRouteImport } from './routes/_authenticated/painel.jogador.competicao'
import { Route as AuthenticatedPainelProfessorCompeticaoIdRouteImport } from './routes/_authenticated/painel.professor.competicao.$id'
import { Route as AuthenticatedPainelProfessorConduzirCompeticaoEquipaRouteImport } from './routes/_authenticated/painel.professor.conduzir.$competicao.$equipa'

const EntrarHansaRoute = EntrarHansaRouteImport.update({
  id: '/entrar-hansa',
  path: '/entrar-hansa',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmadoRoute = AuthConfirmadoRouteImport.update({
  id: '/confirmado',
  path: '/confirmado',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedNovaHansaRoute = AuthenticatedNovaHansaRouteImport.update({
  id: '/nova-hansa',
  path: '/nova-hansa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/painel/',
    path: '/painel/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelSuperAdminRoute =
  AuthenticatedPainelSuperAdminRouteImport.update({
    id: '/painel/super-admin',
    path: '/painel/super-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelJogadorHomeRoute =
  AuthenticatedPainelJogadorHomeRouteImport.update({
    id: '/painel/jogador-home',
    path: '/painel/jogador-home',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelAdminEscolarRoute =
  AuthenticatedPainelAdminEscolarRouteImport.update({
    id: '/painel/admin-escolar',
    path: '/painel/admin-escolar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelProfessorIndexRoute =
  AuthenticatedPainelProfessorIndexRouteImport.update({
    id: '/painel/professor/',
    path: '/painel/professor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelJogadorIndexRoute =
  AuthenticatedPainelJogadorIndexRouteImport.update({
    id: '/painel/jogador/',
    path: '/painel/jogador/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksResolverTickRoute =
  ApiPublicHooksResolverTickRouteImport.update({
    id: '/api/public/hooks/resolver-tick',
    path: '/api/public/hooks/resolver-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPainelJogadorCompeticaoRoute =
  AuthenticatedPainelJogadorCompeticaoRouteImport.update({
    id: '/painel/jogador/competicao',
    path: '/painel/jogador/competicao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelProfessorCompeticaoIdRoute =
  AuthenticatedPainelProfessorCompeticaoIdRouteImport.update({
    id: '/painel/professor/competicao/$id',
    path: '/painel/professor/competicao/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelProfessorConduzirCompeticaoEquipaRoute =
  AuthenticatedPainelProfessorConduzirCompeticaoEquipaRouteImport.update({
    id: '/painel/professor/conduzir/$competicao/$equipa',
    path: '/painel/professor/conduzir/$competicao/$equipa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/demo': typeof DemoRoute
  '/entrar-hansa': typeof EntrarHansaRoute
  '/nova-hansa': typeof AuthenticatedNovaHansaRoute
  '/auth/confirmado': typeof AuthConfirmadoRoute
  '/painel/admin-escolar': typeof AuthenticatedPainelAdminEscolarRoute
  '/painel/jogador-home': typeof AuthenticatedPainelJogadorHomeRoute
  '/painel/super-admin': typeof AuthenticatedPainelSuperAdminRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/painel/jogador/competicao': typeof AuthenticatedPainelJogadorCompeticaoRoute
  '/api/public/hooks/resolver-tick': typeof ApiPublicHooksResolverTickRoute
  '/painel/jogador/': typeof AuthenticatedPainelJogadorIndexRoute
  '/painel/professor/': typeof AuthenticatedPainelProfessorIndexRoute
  '/painel/professor/competicao/$id': typeof AuthenticatedPainelProfessorCompeticaoIdRoute
  '/painel/professor/conduzir/$competicao/$equipa': typeof AuthenticatedPainelProfessorConduzirCompeticaoEquipaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/demo': typeof DemoRoute
  '/entrar-hansa': typeof EntrarHansaRoute
  '/nova-hansa': typeof AuthenticatedNovaHansaRoute
  '/auth/confirmado': typeof AuthConfirmadoRoute
  '/painel/admin-escolar': typeof AuthenticatedPainelAdminEscolarRoute
  '/painel/jogador-home': typeof AuthenticatedPainelJogadorHomeRoute
  '/painel/super-admin': typeof AuthenticatedPainelSuperAdminRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/painel/jogador/competicao': typeof AuthenticatedPainelJogadorCompeticaoRoute
  '/api/public/hooks/resolver-tick': typeof ApiPublicHooksResolverTickRoute
  '/painel/jogador': typeof AuthenticatedPainelJogadorIndexRoute
  '/painel/professor': typeof AuthenticatedPainelProfessorIndexRoute
  '/painel/professor/competicao/$id': typeof AuthenticatedPainelProfessorCompeticaoIdRoute
  '/painel/professor/conduzir/$competicao/$equipa': typeof AuthenticatedPainelProfessorConduzirCompeticaoEquipaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/demo': typeof DemoRoute
  '/entrar-hansa': typeof EntrarHansaRoute
  '/_authenticated/nova-hansa': typeof AuthenticatedNovaHansaRoute
  '/auth/confirmado': typeof AuthConfirmadoRoute
  '/_authenticated/painel/admin-escolar': typeof AuthenticatedPainelAdminEscolarRoute
  '/_authenticated/painel/jogador-home': typeof AuthenticatedPainelJogadorHomeRoute
  '/_authenticated/painel/super-admin': typeof AuthenticatedPainelSuperAdminRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/_authenticated/painel/jogador/competicao': typeof AuthenticatedPainelJogadorCompeticaoRoute
  '/api/public/hooks/resolver-tick': typeof ApiPublicHooksResolverTickRoute
  '/_authenticated/painel/jogador/': typeof AuthenticatedPainelJogadorIndexRoute
  '/_authenticated/painel/professor/': typeof AuthenticatedPainelProfessorIndexRoute
  '/_authenticated/painel/professor/competicao/$id': typeof AuthenticatedPainelProfessorCompeticaoIdRoute
  '/_authenticated/painel/professor/conduzir/$competicao/$equipa': typeof AuthenticatedPainelProfessorConduzirCompeticaoEquipaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/entrar-hansa'
    | '/nova-hansa'
    | '/auth/confirmado'
    | '/painel/admin-escolar'
    | '/painel/jogador-home'
    | '/painel/super-admin'
    | '/painel/'
    | '/painel/jogador/competicao'
    | '/api/public/hooks/resolver-tick'
    | '/painel/jogador/'
    | '/painel/professor/'
    | '/painel/professor/competicao/$id'
    | '/painel/professor/conduzir/$competicao/$equipa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/entrar-hansa'
    | '/nova-hansa'
    | '/auth/confirmado'
    | '/painel/admin-escolar'
    | '/painel/jogador-home'
    | '/painel/super-admin'
    | '/painel'
    | '/painel/jogador/competicao'
    | '/api/public/hooks/resolver-tick'
    | '/painel/jogador'
    | '/painel/professor'
    | '/painel/professor/competicao/$id'
    | '/painel/professor/conduzir/$competicao/$equipa'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo'
    | '/entrar-hansa'
    | '/_authenticated/nova-hansa'
    | '/auth/confirmado'
    | '/_authenticated/painel/admin-escolar'
    | '/_authenticated/painel/jogador-home'
    | '/_authenticated/painel/super-admin'
    | '/_authenticated/painel/'
    | '/_authenticated/painel/jogador/competicao'
    | '/api/public/hooks/resolver-tick'
    | '/_authenticated/painel/jogador/'
    | '/_authenticated/painel/professor/'
    | '/_authenticated/painel/professor/competicao/$id'
    | '/_authenticated/painel/professor/conduzir/$competicao/$equipa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DemoRoute: typeof DemoRoute
  EntrarHansaRoute: typeof EntrarHansaRoute
  ApiPublicHooksResolverTickRoute: typeof ApiPublicHooksResolverTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/entrar-hansa': {
      id: '/entrar-hansa'
      path: '/entrar-hansa'
      fullPath: '/entrar-hansa'
      preLoaderRoute: typeof EntrarHansaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirmado': {
      id: '/auth/confirmado'
      path: '/confirmado'
      fullPath: '/auth/confirmado'
      preLoaderRoute: typeof AuthConfirmadoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/nova-hansa': {
      id: '/_authenticated/nova-hansa'
      path: '/nova-hansa'
      fullPath: '/nova-hansa'
      preLoaderRoute: typeof AuthenticatedNovaHansaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/super-admin': {
      id: '/_authenticated/painel/super-admin'
      path: '/painel/super-admin'
      fullPath: '/painel/super-admin'
      preLoaderRoute: typeof AuthenticatedPainelSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/jogador-home': {
      id: '/_authenticated/painel/jogador-home'
      path: '/painel/jogador-home'
      fullPath: '/painel/jogador-home'
      preLoaderRoute: typeof AuthenticatedPainelJogadorHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/admin-escolar': {
      id: '/_authenticated/painel/admin-escolar'
      path: '/painel/admin-escolar'
      fullPath: '/painel/admin-escolar'
      preLoaderRoute: typeof AuthenticatedPainelAdminEscolarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/professor/': {
      id: '/_authenticated/painel/professor/'
      path: '/painel/professor'
      fullPath: '/painel/professor/'
      preLoaderRoute: typeof AuthenticatedPainelProfessorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/jogador/': {
      id: '/_authenticated/painel/jogador/'
      path: '/painel/jogador'
      fullPath: '/painel/jogador/'
      preLoaderRoute: typeof AuthenticatedPainelJogadorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/resolver-tick': {
      id: '/api/public/hooks/resolver-tick'
      path: '/api/public/hooks/resolver-tick'
      fullPath: '/api/public/hooks/resolver-tick'
      preLoaderRoute: typeof ApiPublicHooksResolverTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/jogador/competicao': {
      id: '/_authenticated/painel/jogador/competicao'
      path: '/painel/jogador/competicao'
      fullPath: '/painel/jogador/competicao'
      preLoaderRoute: typeof AuthenticatedPainelJogadorCompeticaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/professor/competicao/$id': {
      id: '/_authenticated/painel/professor/competicao/$id'
      path: '/painel/professor/competicao/$id'
      fullPath: '/painel/professor/competicao/$id'
      preLoaderRoute: typeof AuthenticatedPainelProfessorCompeticaoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/professor/conduzir/$competicao/$equipa': {
      id: '/_authenticated/painel/professor/conduzir/$competicao/$equipa'
      path: '/painel/professor/conduzir/$competicao/$equipa'
      fullPath: '/painel/professor/conduzir/$competicao/$equipa'
      preLoaderRoute: typeof AuthenticatedPainelProfessorConduzirCompeticaoEquipaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNovaHansaRoute: typeof AuthenticatedNovaHansaRoute
  AuthenticatedPainelAdminEscolarRoute: typeof AuthenticatedPainelAdminEscolarRoute
  AuthenticatedPainelJogadorHomeRoute: typeof AuthenticatedPainelJogadorHomeRoute
  AuthenticatedPainelSuperAdminRoute: typeof AuthenticatedPainelSuperAdminRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
  AuthenticatedPainelJogadorCompeticaoRoute: typeof AuthenticatedPainelJogadorCompeticaoRoute
  AuthenticatedPainelJogadorIndexRoute: typeof AuthenticatedPainelJogadorIndexRoute
  AuthenticatedPainelProfessorIndexRoute: typeof AuthenticatedPainelProfessorIndexRoute
  AuthenticatedPainelProfessorCompeticaoIdRoute: typeof AuthenticatedPainelProfessorCompeticaoIdRoute
  AuthenticatedPainelProfessorConduzirCompeticaoEquipaRoute: typeof AuthenticatedPainelProfessorConduzirCompeticaoEquipaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNovaHansaRoute: AuthenticatedNovaHansaRoute,
  AuthenticatedPainelAdminEscolarRoute: AuthenticatedPainelAdminEscolarRoute,
  AuthenticatedPainelJogadorHomeRoute: AuthenticatedPainelJogadorHomeRoute,
  AuthenticatedPainelSuperAdminRoute: AuthenticatedPainelSuperAdminRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
  AuthenticatedPainelJogadorCompeticaoRoute:
    AuthenticatedPainelJogadorCompeticaoRoute,
  AuthenticatedPainelJogadorIndexRoute: AuthenticatedPainelJogadorIndexRoute,
  AuthenticatedPainelProfessorIndexRoute:
    AuthenticatedPainelProfessorIndexRoute,
  AuthenticatedPainelProfessorCompeticaoIdRoute:
    AuthenticatedPainelProfessorCompeticaoIdRoute,
  AuthenticatedPainelProfessorConduzirCompeticaoEquipaRoute:
    AuthenticatedPainelProfessorConduzirCompeticaoEquipaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthConfirmadoRoute: typeof AuthConfirmadoRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmadoRoute: AuthConfirmadoRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DemoRoute: DemoRoute,
  EntrarHansaRoute: EntrarHansaRoute,
  ApiPublicHooksResolverTickRoute: ApiPublicHooksResolverTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
