/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EntrarHansaRouteImport } from './routes/entrar-hansa'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedNovaHansaRouteImport } from './routes/_authenticated/nova-hansa'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedPainelSuperAdminRouteImport } from './routes/_authenticated/painel.super-admin'
import { Route as AuthenticatedPainelProfessorRouteImport } from './routes/_authenticated/painel.professor'
import { Route as AuthenticatedPainelJogadorRouteImport } from './routes/_authenticated/painel.jogador'
import { Route as AuthenticatedPainelAdminEscolarRouteImport } from './routes/_authenticated/painel.admin-escolar'
import { Route as ApiPublicHooksResolverTickRouteImport } from './routes/api/public/hooks/resolver-tick'
import { Route as AuthenticatedPainelProfessorCompeticaoIdRouteImport } from './routes/_authenticated/painel.professor.competicao.$id'

const EntrarHansaRoute = EntrarHansaRouteImport.update({
  id: '/entrar-hansa',
  path: '/entrar-hansa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNovaHansaRoute = AuthenticatedNovaHansaRouteImport.update({
  id: '/nova-hansa',
  path: '/nova-hansa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/painel/',
    path: '/painel/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelSuperAdminRoute =
  AuthenticatedPainelSuperAdminRouteImport.update({
    id: '/painel/super-admin',
    path: '/painel/super-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelProfessorRoute =
  AuthenticatedPainelProfessorRouteImport.update({
    id: '/painel/professor',
    path: '/painel/professor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelJogadorRoute =
  AuthenticatedPainelJogadorRouteImport.update({
    id: '/painel/jogador',
    path: '/painel/jogador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelAdminEscolarRoute =
  AuthenticatedPainelAdminEscolarRouteImport.update({
    id: '/painel/admin-escolar',
    path: '/painel/admin-escolar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksResolverTickRoute =
  ApiPublicHooksResolverTickRouteImport.update({
    id: '/api/public/hooks/resolver-tick',
    path: '/api/public/hooks/resolver-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPainelProfessorCompeticaoIdRoute =
  AuthenticatedPainelProfessorCompeticaoIdRouteImport.update({
    id: '/competicao/$id',
    path: '/competicao/$id',
    getParentRoute: () => AuthenticatedPainelProfessorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/entrar-hansa': typeof EntrarHansaRoute
  '/nova-hansa': typeof AuthenticatedNovaHansaRoute
  '/painel/admin-escolar': typeof AuthenticatedPainelAdminEscolarRoute
  '/painel/jogador': typeof AuthenticatedPainelJogadorRoute
  '/painel/professor': typeof AuthenticatedPainelProfessorRouteWithChildren
  '/painel/super-admin': typeof AuthenticatedPainelSuperAdminRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/api/public/hooks/resolver-tick': typeof ApiPublicHooksResolverTickRoute
  '/painel/professor/competicao/$id': typeof AuthenticatedPainelProfessorCompeticaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/entrar-hansa': typeof EntrarHansaRoute
  '/nova-hansa': typeof AuthenticatedNovaHansaRoute
  '/painel/admin-escolar': typeof AuthenticatedPainelAdminEscolarRoute
  '/painel/jogador': typeof AuthenticatedPainelJogadorRoute
  '/painel/professor': typeof AuthenticatedPainelProfessorRouteWithChildren
  '/painel/super-admin': typeof AuthenticatedPainelSuperAdminRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/api/public/hooks/resolver-tick': typeof ApiPublicHooksResolverTickRoute
  '/painel/professor/competicao/$id': typeof AuthenticatedPainelProfessorCompeticaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/entrar-hansa': typeof EntrarHansaRoute
  '/_authenticated/nova-hansa': typeof AuthenticatedNovaHansaRoute
  '/_authenticated/painel/admin-escolar': typeof AuthenticatedPainelAdminEscolarRoute
  '/_authenticated/painel/jogador': typeof AuthenticatedPainelJogadorRoute
  '/_authenticated/painel/professor': typeof AuthenticatedPainelProfessorRouteWithChildren
  '/_authenticated/painel/super-admin': typeof AuthenticatedPainelSuperAdminRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/api/public/hooks/resolver-tick': typeof ApiPublicHooksResolverTickRoute
  '/_authenticated/painel/professor/competicao/$id': typeof AuthenticatedPainelProfessorCompeticaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/entrar-hansa'
    | '/nova-hansa'
    | '/painel/admin-escolar'
    | '/painel/jogador'
    | '/painel/professor'
    | '/painel/super-admin'
    | '/painel/'
    | '/api/public/hooks/resolver-tick'
    | '/painel/professor/competicao/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/entrar-hansa'
    | '/nova-hansa'
    | '/painel/admin-escolar'
    | '/painel/jogador'
    | '/painel/professor'
    | '/painel/super-admin'
    | '/painel'
    | '/api/public/hooks/resolver-tick'
    | '/painel/professor/competicao/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/entrar-hansa'
    | '/_authenticated/nova-hansa'
    | '/_authenticated/painel/admin-escolar'
    | '/_authenticated/painel/jogador'
    | '/_authenticated/painel/professor'
    | '/_authenticated/painel/super-admin'
    | '/_authenticated/painel/'
    | '/api/public/hooks/resolver-tick'
    | '/_authenticated/painel/professor/competicao/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EntrarHansaRoute: typeof EntrarHansaRoute
  ApiPublicHooksResolverTickRoute: typeof ApiPublicHooksResolverTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/entrar-hansa': {
      id: '/entrar-hansa'
      path: '/entrar-hansa'
      fullPath: '/entrar-hansa'
      preLoaderRoute: typeof EntrarHansaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nova-hansa': {
      id: '/_authenticated/nova-hansa'
      path: '/nova-hansa'
      fullPath: '/nova-hansa'
      preLoaderRoute: typeof AuthenticatedNovaHansaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/super-admin': {
      id: '/_authenticated/painel/super-admin'
      path: '/painel/super-admin'
      fullPath: '/painel/super-admin'
      preLoaderRoute: typeof AuthenticatedPainelSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/professor': {
      id: '/_authenticated/painel/professor'
      path: '/painel/professor'
      fullPath: '/painel/professor'
      preLoaderRoute: typeof AuthenticatedPainelProfessorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/jogador': {
      id: '/_authenticated/painel/jogador'
      path: '/painel/jogador'
      fullPath: '/painel/jogador'
      preLoaderRoute: typeof AuthenticatedPainelJogadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/admin-escolar': {
      id: '/_authenticated/painel/admin-escolar'
      path: '/painel/admin-escolar'
      fullPath: '/painel/admin-escolar'
      preLoaderRoute: typeof AuthenticatedPainelAdminEscolarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/resolver-tick': {
      id: '/api/public/hooks/resolver-tick'
      path: '/api/public/hooks/resolver-tick'
      fullPath: '/api/public/hooks/resolver-tick'
      preLoaderRoute: typeof ApiPublicHooksResolverTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/professor/competicao/$id': {
      id: '/_authenticated/painel/professor/competicao/$id'
      path: '/competicao/$id'
      fullPath: '/painel/professor/competicao/$id'
      preLoaderRoute: typeof AuthenticatedPainelProfessorCompeticaoIdRouteImport
      parentRoute: typeof AuthenticatedPainelProfessorRoute
    }
  }
}

interface AuthenticatedPainelProfessorRouteChildren {
  AuthenticatedPainelProfessorCompeticaoIdRoute: typeof AuthenticatedPainelProfessorCompeticaoIdRoute
}

const AuthenticatedPainelProfessorRouteChildren: AuthenticatedPainelProfessorRouteChildren =
  {
    AuthenticatedPainelProfessorCompeticaoIdRoute:
      AuthenticatedPainelProfessorCompeticaoIdRoute,
  }

const AuthenticatedPainelProfessorRouteWithChildren =
  AuthenticatedPainelProfessorRoute._addFileChildren(
    AuthenticatedPainelProfessorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNovaHansaRoute: typeof AuthenticatedNovaHansaRoute
  AuthenticatedPainelAdminEscolarRoute: typeof AuthenticatedPainelAdminEscolarRoute
  AuthenticatedPainelJogadorRoute: typeof AuthenticatedPainelJogadorRoute
  AuthenticatedPainelProfessorRoute: typeof AuthenticatedPainelProfessorRouteWithChildren
  AuthenticatedPainelSuperAdminRoute: typeof AuthenticatedPainelSuperAdminRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNovaHansaRoute: AuthenticatedNovaHansaRoute,
  AuthenticatedPainelAdminEscolarRoute: AuthenticatedPainelAdminEscolarRoute,
  AuthenticatedPainelJogadorRoute: AuthenticatedPainelJogadorRoute,
  AuthenticatedPainelProfessorRoute:
    AuthenticatedPainelProfessorRouteWithChildren,
  AuthenticatedPainelSuperAdminRoute: AuthenticatedPainelSuperAdminRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EntrarHansaRoute: EntrarHansaRoute,
  ApiPublicHooksResolverTickRoute: ApiPublicHooksResolverTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
